link0:
  origin:
    x: 0.000319  # 米
    y: 0.000670  # 米
    z: 0.029184  # 米
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 1.772680  # 千克
  inertia:
    xx: 0.002463  # 千克 * 平方米
    xy: 0.000027  # 千克 * 平方米
    xz: 0.000018  # 千克 * 平方米
    yy: 0.001962  # 千克 * 平方米
    yz: 0.000036  # 千克 * 平方米
    zz: 0.003414  # 千克 * 平方米

link1:
  origin:
    x: 0.004452  # 米
    y: -0.000025  # 米
    z: 0.073323  # 米
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 1.688763  # 千克
  inertia:
    xx: 0.003463  # 千克 * 平方米
    xy: 0.000002  # 千克 * 平方米
    xz: 0.000098  # 千克 * 平方米
    yy: 0.002551  # 千克 * 平方米
    yz: 0.000001  # 千克 * 平方米
    zz: 0.001916  # 千克 * 平方米

link2:
  origin:
    x: -0.003787  # 米
    y: 0.000221  # 米
    z: 0.049010  # 米
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 0.396704  # 千克
  inertia:
    xx: 0.000834  # 千克 * 平方米
    xy: -0.000001  # 千克 * 平方米
    xz: 0.000170  # 千克 * 平方米
    yy: 0.000822  # 千克 * 平方米
    yz: -0.000005  # 千克 * 平方米
    zz: 0.000385  # 千克 * 平方米

link3:
  origin:
    x: -0.000828  # 米
    y: 0.000236  # 米
    z: 0.083336  # 米
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 2.492784  # 千克
  inertia:
    xx: 0.010352  # 千克 * 平方米
    xy: -0.000015  # 千克 * 平方米
    xz: -0.000034  # 千克 * 平方米
    yy: 0.010343  # 千克 * 平方米
    yz: 0.000094  # 千克 * 平方米
    zz: 0.003003  # 千克 * 平方米

link4:
  origin:
    x: -0.002591  # 米
    y: -0.030135  # 米
    z: 0.071470  # 米
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 0.779755  # 千克
  inertia:
    xx: 0.002015  # 千克 * 平方米
    xy: 0.000000  # 千克 * 平方米
    xz: 0.000023  # 千克 * 平方米
    yy: 0.001620  # 千克 * 平方米
    yz: -0.000040  # 千克 * 平方米
    zz: 0.000768  # 千克 * 平方米

link5:
  origin:
    x: -0.002256  # 米
    y: 0.000305  # 米
    z: 0.053300  # 米
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 0.687255  # 千克
  inertia:
    xx: 0.000831  # 千克 * 平方米
    xy: 0.000005  # 千克 * 平方米
    xz: 0.000011  # 千克 * 平方米
    yy: 0.001066  # 千克 * 平方米
    yz: -0.000001  # 千克 * 平方米
    zz: 0.000496  # 千克 * 平方米

link6:
  origin:
    x: -0.035640  # 米
    y: -0.005114  # 米
    z: -0.003582  # 米
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 0.384836  # 千克
  inertia:
    xx: 0.000292  # 千克 * 平方米
    xy: -0.000017  # 千克 * 平方米
    xz: -0.000032  # 千克 * 平方米
    yy: 0.000276  # 千克 * 平方米
    yz: 0.000018  # 千克 * 平方米
    zz: 0.000227  # 千克 * 平方米

link7:
  origin:
    x: -0.000003  # 米
    y: 0.002128  # 米
    z: 0.091961  # 米
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 0.624972  # 千克
  inertia:
    xx: 0.001598  # 千克 * 平方米
    xy: -0.000050  # 千克 * 平方米
    xz: 0.000000  # 千克 * 平方米
    yy: 0.001067  # 千克 * 平方米
    yz: -0.000087  # 千克 * 平方米
    zz: 0.000784  # 千克 * 平方米